name: Build LaTeX Document and push to Dropbox
on: [ push ]

jobs:
  build:
    name: Build LaTeX Document and push to Dropbox
    runs-on: ubuntu-latest
    container: kjarosh/latex:2025.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p out

      - name: Build using latexmk
        run: xelatex -jobname=resume -output-directory=out resume.tex

      - name: Set DATE variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Upload file to Dropbox
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          curl -X POST https://content.dropboxapi.com/2/files/upload \
          --header "Authorization: Bearer $DROPBOX_TOKEN" \
          --header "Dropbox-API-Arg: {\"path\": \"/Resume/Ehsan_Seyedi_Resume_${{ env.DATE }}.pdf\",\"mode\": \"add\",\"autorename\": true,\"mute\": false}" \
          --header "Content-Type: application/octet-stream" \
          --data-binary @out/resume.pdf
